[package]
name = "c0mpiler"
version = "0.1.0"
edition = "2024"

[dependencies]
enum-as-inner = "0.6.1"
fancy-regex = "0.16.1"
paste = { package = "pastey", version = "*" }
regex = "1.11.2"
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
